
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS PRESTAMO;


CREATE TABLE USUARIO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL,
        dni VARCHAR(10) NOT NULL,
        telefono INT NOT NULL  ) ;

CREATE TABLE LIBRO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(25) NOT NULL ,
	isbn VARCHAR (25) NOT NULL,
        escritor VARCHAR(25) NOT NULL,
        editorial VARCHAR(30) NOT NULL);

CREATE TABLE PRESTAMO(
        USUARIO INT,
        LIBRO INT,
        DIAS INT,
        PRIMARY KEY (USUARIO, LIBRO),
        FOREIGN KEY (USUARIO) REFERENCES USUARIO(id),
        FOREIGN KEY (LIBRO) REFERENCES LIBRO(id));

INSERT INTO USUARIO VALUES (NULL,'PEPE','PEREZ','11111111A',677374626);
INSERT INTO USUARIO VALUES (NULL,'JOSE','RAMIREZ','22222222A',658748555);
INSERT INTO USUARIO VALUES (NULL,'ANGEL','CANSADO','33333333A',758444251);
INSERT INTO USUARIO VALUES (NULL,'SONIA','SERRANO','44444444A',625888474);

INSERT INTO LIBRO VALUES (NULL,'EMOCIONADO','9788494151309','RAFAEL ROMERO','PALABRAS ALADAS');
INSERT INTO LIBRO VALUES (NULL,'MOBILE MARKETING','9788494585500','JESUS HERNANDEZ','PUBLIXED MEDIA BLUE S.L.');
INSERT INTO LIBRO VALUES (NULL,'EL GUARDIÁN INVISIBLE','9788423351893','DOLORES REDONDO','DESTINO');
INSERT INTO LIBRO VALUES (NULL,'LA VÍSPERA DE CASI TODO','9788423351879','VICTOR DEL ARBOL','DESTINO');

